# Set of constants shared by various modules

COMMS_NOERROR = 0
COMMS_ERROR_SERIAL = 1 << 0
COMMS_ERROR_TCP = 1 << 1
COMMS_ERROR_SERIAL_INITIALISATION = 1 << 2
COMMS_ERROR_TCP_INITIALISATION = 1 << 3
COMMS_ERROR_TCP_TIMEOUT = 1 << 4

# Buffer size of StreamReaders.
READBUFFER = 256

CARRIER_DETECT_UNDEFINED = 0
CARRIER_DETECT_YES = 1
CARRIER_DETECT_NO = 2        
